<script>
	import Bylines from "./Bylines.svelte";
	import Photo from "./Photo.svelte";

</script>
<article>

    <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi, iure?</h1>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Minus itaque iusto praesentium commodi officia perspiciatis aspernatur ipsam? Possimus, id a!</h2>
    <Photo />
    <Bylines />
    <div class="story">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo sint autem error, odit similique ratione possimus! Distinctio possimus nostrum quaerat odit nihil iusto dolorum, dignissimos quam soluta, delectus quo eos eligendi, suscipit ut beatae enim earum tempora culpa fugit! Nam incidunt ipsum velit aut atque quae magni iste mollitia laboriosam error dolorem maxime dignissimos rerum, enim delectus est? Nihil voluptates labore rem ab. Commodi laudantium dolor, ducimus ea consequuntur deleniti officia corporis, dicta id voluptatibus beatae alias exercitationem ab quisquam neque fugit aspernatur dolore eligendi sit laborum perferendis! Eius laborum adipisci iusto quo cupiditate temporibus neque quam unde vero quasi eaque, ullam, dolores consectetur voluptate! Ex optio qui blanditiis nisi architecto omnis, possimus repellat corrupti, veritatis a sunt aut culpa eos aspernatur, rem dicta ipsam quis sequi nemo? Explicabo sit voluptatibus, id consectetur placeat molestias eos amet, blanditiis voluptatem aliquam, ducimus magnam eveniet rem quas corrupti eum suscipit nisi asperiores dicta fugit vero illo in reprehenderit perspiciatis. Porro amet quisquam itaque ab deserunt totam repellat enim quo non ipsam nihil nam ratione, atque officia blanditiis voluptatibus quis optio quae quam ullam nemo vel delectus numquam corrupti! Sunt nam perferendis voluptatum, facilis omnis modi labore earum, vitae praesentium dolores, error officia.</p>
        <p>Fuga inventore aperiam facere consectetur! Inventore, beatae? Officia, cum adipisci! Quam aliquid provident odio! Dolorem velit aspernatur consequatur laborum ducimus perferendis, animi est iure quasi, quam labore? Magni, quidem? Commodi perspiciatis et eum alias necessitatibus recusandae dignissimos praesentium fugiat quidem sed dolorem in, blanditiis quas culpa animi error impedit. Officiis harum accusamus deleniti nam perspiciatis fugiat quae dolore, neque, rem sequi autem voluptate quod ab consequatur, temporibus est deserunt aperiam consectetur consequuntur. Temporibus, ratione totam quis minus maxime corrupti voluptas consectetur aliquam optio deserunt saepe, incidunt quae obcaecati, veniam nihil eveniet assumenda sit reiciendis accusamus officia deleniti! Perferendis illo dignissimos inventore cum amet optio ducimus ipsum quaerat, ullam, ab est nobis saepe voluptatum dolore. Ex saepe veniam quos! Totam voluptate quaerat doloribus repellat, quas molestias amet, iure dolore libero ducimus repellendus doloremque rem vel dignissimos eaque, expedita omnis debitis! Nihil eos, perferendis maiores omnis reprehenderit illum, dolores similique et pariatur repellat minus voluptatibus vel. Explicabo voluptatem quibusdam voluptates, ipsa quasi sed in. Dolorum veritatis ducimus cupiditate possimus consectetur repudiandae suscipit nihil sunt eligendi, vero reprehenderit autem necessitatibus perspiciatis accusantium deserunt quos ipsam consequuntur delectus non corporis impedit maiores? Voluptatum eos iusto sint quisquam sit distinctio maxime quae cumque cupiditate! Eaque?</p>
        <p>Tenetur facilis magni repudiandae magnam soluta illo corrupti porro ipsam recusandae dolore quo animi temporibus nihil ad doloremque quis, reprehenderit possimus cum! Laboriosam enim, temporibus ipsam obcaecati doloribus eos sint alias cupiditate maxime! Mollitia consequatur tenetur fugit cumque porro optio saepe commodi blanditiis odit nemo, perferendis qui, aspernatur illum est quisquam, ducimus sunt? Vel nobis ipsa, cumque ab quod nostrum sint. Sit odio, corrupti natus, provident tenetur quis enim totam voluptatibus consectetur impedit fugit quaerat similique culpa quibusdam harum aliquid vero, laboriosam ipsum! Eum numquam distinctio quisquam quia porro doloribus totam id maxime, harum similique odio? Nulla at voluptatibus atque necessitatibus nostrum aliquam eos animi tempora repellendus fuga magni beatae neque natus, voluptate nisi enim, unde eum aperiam aliquid magnam sapiente ratione dolores. Quam deserunt laborum aliquid iste in blanditiis voluptatem assumenda similique? Sed ducimus itaque eligendi neque provident assumenda explicabo, magnam suscipit deserunt. Deserunt dolor debitis ducimus. Illum optio eligendi asperiores natus veritatis possimus dicta maxime, omnis veniam consequuntur fuga nobis similique labore, quas ipsam. Sunt alias quas repellat dignissimos at ipsa deserunt totam mollitia quam atque accusantium vel rem unde laboriosam, repellendus reprehenderit enim doloremque. Eos repellat fuga harum corrupti tempora facilis ex dolorem recusandae natus, quasi explicabo.</p>
        <p>Quasi necessitatibus corrupti vel sed ut exercitationem expedita incidunt consequatur, similique id voluptate dicta ab ducimus autem voluptatem quos itaque sint natus tempore fugit neque pariatur non excepturi. Quae consequatur, deleniti assumenda autem perferendis earum quia, unde recusandae odit ea et distinctio reprehenderit officia itaque esse consectetur beatae molestias voluptatum aliquid provident. Earum labore totam sint velit. Rem magni aliquam consequuntur sunt repellat qui labore illo assumenda pariatur possimus culpa voluptatem, nulla, ipsam, sit est a obcaecati tenetur iste minima id cum! Qui beatae sed fugiat veniam est, laborum quas dignissimos natus eveniet commodi molestiae, vero quos iure eos voluptatibus. Aspernatur cupiditate unde consequuntur. Corrupti, nostrum inventore. Libero aliquam omnis deleniti unde vitae sit? Pariatur quia vel quis, quibusdam eos voluptatibus delectus autem saepe est consequatur ducimus porro! Esse corrupti omnis commodi inventore eos vel nostrum eligendi? Est, recusandae maiores. Obcaecati nesciunt a voluptatem cum laudantium eius? Ducimus sunt dolores voluptas adipisci, iure nihil consequatur, nostrum officiis odit maiores illum distinctio molestiae et. Quisquam quod repellendus et labore, tempore praesentium dolores minima porro consequuntur itaque. Mollitia, consequatur porro repellat delectus distinctio consequuntur quos perferendis dolorem tempora excepturi vero rem. Libero voluptas doloribus molestiae sunt, earum in consequatur odit at possimus.</p>
        <p>Provident cumque est maiores rem, nostrum eius officia expedita, vitae ipsum quisquam neque enim eligendi velit! Distinctio quisquam quis saepe optio dolorem in, voluptates reiciendis animi nisi non quae molestias ullam! Quis eveniet sint deserunt beatae quae dolor et eaque corporis adipisci. Perferendis nisi natus, necessitatibus nesciunt incidunt amet cupiditate saepe reiciendis inventore ut expedita rerum numquam atque eaque excepturi consectetur corrupti porro ducimus. Distinctio labore, quidem quae quisquam expedita quas voluptatum hic quia omnis dignissimos magni corporis, nam animi modi perspiciatis molestiae praesentium nobis est at, non qui quaerat rerum commodi dolore? Ipsa corrupti deleniti esse explicabo praesentium dolorem unde quos officia suscipit labore laborum facere soluta doloremque, tempore sapiente minus alias perspiciatis fuga similique obcaecati dolore cum consequuntur dolores? Veniam temporibus, in hic perferendis animi neque, tempore ab laborum reprehenderit, debitis nihil! Repellendus tenetur sapiente nobis temporibus, non quis. Nihil tempora ducimus, nam dolores ratione, magni veritatis explicabo dolorum provident molestiae officiis laudantium qui recusandae enim ullam velit molestias obcaecati dolorem quia rerum. Soluta dolorum doloremque omnis tempora error maxime molestiae esse illo, saepe quisquam voluptates nisi aliquam odio vel qui cum minima quo rem accusamus labore molestias fuga quaerat. Ullam delectus quas numquam porro at, quibusdam reiciendis.</p>
        <p>Modi possimus enim, qui hic quam tempore reiciendis officia nisi dignissimos eveniet, dolores perspiciatis quibusdam assumenda autem facilis ducimus labore illo ullam? Vel fuga voluptas culpa exercitationem voluptatibus provident harum porro architecto nobis sapiente quam iusto, laudantium reprehenderit sint ullam officia at placeat asperiores minus corrupti? Ut distinctio voluptates maiores perspiciatis magnam vero tempora, commodi hic earum nulla praesentium culpa doloribus animi pariatur quibusdam saepe harum eos molestiae iure. Autem error, est magnam, nostrum vitae sequi voluptatibus suscipit earum libero nisi doloremque, praesentium enim necessitatibus natus quae eaque eveniet deserunt quibusdam hic illum. Laudantium neque magni vel ipsum ab est quas debitis maiores, nostrum tempora voluptate dolorem hic saepe? Nihil tempora amet architecto tempore soluta neque explicabo corporis, adipisci possimus alias nostrum numquam quod, eligendi nobis natus quaerat debitis sed consectetur reiciendis! Assumenda adipisci molestias nihil. Neque dolores sapiente iste dignissimos. Consectetur asperiores eligendi facilis ipsa, dolor a pariatur officia et explicabo veritatis illum. Enim, obcaecati similique? In eius velit error consequatur fugit, ut eveniet corrupti ullam ipsam enim obcaecati fuga adipisci eaque nostrum temporibus quam neque harum esse sint voluptatum atque dolor aspernatur magnam. Aliquam illo libero officia, exercitationem repellendus at nemo similique, laborum labore quisquam aut minus dicta!</p>
        <p>Dolorem possimus ducimus aut voluptatum? Hic provident fugit eius quo rem culpa sequi id unde vitae quisquam sapiente facilis eligendi perspiciatis temporibus sunt earum cumque sit excepturi quibusdam, dolor magni blanditiis. Dolore minima consequuntur eveniet, tempore officia dolores molestiae reiciendis, hic aliquid illum sit perferendis reprehenderit expedita! Ad minima, eum aperiam voluptates quis vel corporis nulla possimus molestias dolor ut iure eius earum non dolorem. Dignissimos reiciendis laudantium est dolorum quidem ipsum ipsa sit! Magni, officiis. Dolorem incidunt neque culpa non quisquam placeat voluptates. Soluta, qui quisquam deserunt maiores tenetur fugit quis accusamus velit sint, iure ipsam sapiente provident incidunt vero veniam at odio facere eveniet, corrupti quae repudiandae possimus. Culpa expedita dolorem assumenda placeat consequuntur laudantium ipsa error dolor, harum inventore. Temporibus, optio! Veritatis, doloremque aspernatur saepe eligendi numquam quas! A illum dolorem, recusandae neque eveniet molestiae fugiat error molestias repellendus eaque? Eligendi, iusto eaque! Placeat, dignissimos quibusdam commodi earum hic exercitationem harum. Quibusdam voluptate est adipisci obcaecati repellendus vitae ab, veniam saepe, molestias voluptatum architecto quisquam enim a accusantium assumenda rem ex debitis! Pariatur nulla tempora consequuntur ipsam debitis, voluptas ducimus. Sunt corrupti, perspiciatis quod numquam corporis aut voluptates perferendis deleniti excepturi in officiis tempora cupiditate vitae vero.</p>
        <p>Atque nisi possimus hic quae sunt, voluptates odit! Neque, reiciendis veritatis quos porro, dolorum amet officiis odit minus voluptatem tempore magni eos itaque repudiandae natus eius architecto! Aperiam officia minus dicta inventore dignissimos vitae doloremque nisi sint aliquid fuga corporis ad consequuntur, animi reiciendis nemo in reprehenderit libero iusto velit. Earum inventore quis quidem quia animi laudantium numquam laboriosam natus suscipit possimus quo ullam vero ut voluptas vel, expedita iure voluptatum, ea error officia aspernatur? Beatae ad sequi eius dolores, ducimus vero magnam est qui? Magnam ratione repudiandae optio excepturi officia, cum illo autem eveniet possimus aut quia pariatur voluptatibus sequi laboriosam deserunt, voluptatum, hic explicabo placeat voluptas tenetur. Natus facere dolores est quam, animi ipsa. Distinctio corporis ad harum dolore voluptates dolor autem, nisi labore quas ducimus aspernatur, vitae perspiciatis quia expedita odio aliquam voluptatem. Nostrum illum ea voluptates animi quis, velit eius est soluta unde temporibus hic dolorem et provident autem harum accusantium nihil exercitationem eum iste atque? Ea animi beatae amet eos perspiciatis necessitatibus ut vero fugiat explicabo ratione eaque consequuntur laudantium quam impedit obcaecati a nihil, mollitia veniam in, atque adipisci modi incidunt. Labore fugiat exercitationem quisquam suscipit pariatur voluptas ad voluptate laborum, voluptatibus distinctio tempore.</p>
        <p>At laboriosam fugit, corrupti veniam exercitationem ullam temporibus eaque, blanditiis asperiores ipsam corporis. Neque, accusantium mollitia, perspiciatis doloribus odio quidem unde cumque consectetur sunt repudiandae harum. Delectus nisi ullam nihil dignissimos explicabo facere consequatur quas id vero illum. Pariatur, blanditiis reprehenderit amet nostrum, explicabo labore id nihil animi distinctio quaerat doloremque debitis ratione maxime tempore delectus iure accusantium voluptate, fugit ea tenetur. Possimus, quos? Laudantium quaerat expedita velit excepturi quia quos placeat corrupti exercitationem hic, molestiae reprehenderit eligendi temporibus sed? Minima, necessitatibus odio placeat sint optio veniam quibusdam culpa ducimus a excepturi possimus consequuntur amet iure ad quasi nihil in dolor laboriosam porro quis nesciunt atque hic corrupti! Totam dolorem placeat maiores facilis iure eveniet! Accusamus aut eaque deleniti reiciendis enim quo repellendus adipisci fugit obcaecati quas odit soluta sunt dolores, repellat expedita cumque aliquam doloremque nihil reprehenderit impedit laboriosam, labore aperiam earum pariatur. Repellat, eum, quas nesciunt commodi ipsam provident sunt sit quaerat hic placeat similique quia perferendis. Nemo fugit ex temporibus asperiores, animi in minus. Nihil beatae esse quod adipisci expedita, ipsa facilis architecto amet facere corrupti laudantium ab maiores natus, eum sint velit tenetur dolore maxime quis recusandae rem corporis dicta. Quisquam aperiam eveniet rerum illo ex.</p>
        <p>Repudiandae, repellat quas? Quis deleniti reprehenderit corporis quibusdam, qui eum doloremque repellendus saepe eligendi accusantium veritatis laudantium suscipit cupiditate autem amet illo optio! Fugit tempora in dolores vel reprehenderit suscipit porro ratione, alias quaerat magnam et unde fuga sapiente impedit modi nesciunt, iusto ipsa ad cum, exercitationem nostrum itaque quo? Cum, ratione ut? Corporis dolore pariatur sequi impedit quas, harum temporibus nisi libero alias sint illo maxime est consequatur ducimus voluptatum maiores laboriosam dolorem eligendi non. Aliquam blanditiis facere ea repellendus sint dolorem nobis amet, mollitia nostrum tenetur accusantium perspiciatis veritatis doloremque quaerat, nulla quibusdam libero necessitatibus odio inventore velit quod consectetur ullam sed? Iste laudantium voluptates ipsa perspiciatis distinctio fuga aspernatur mollitia qui amet ad dolore, minus accusamus sint non asperiores earum id nihil facilis adipisci libero commodi nisi necessitatibus recusandae tempora! Iste architecto corrupti non excepturi, sapiente praesentium nesciunt rerum eaque, iusto odit omnis minus qui molestias tempora in autem beatae, aliquid atque dolorem. Omnis temporibus, quam modi quasi iure repudiandae laborum! Pariatur fugiat alias delectus ducimus illum asperiores. Amet laboriosam magni architecto animi quis! Repellat ducimus porro eveniet beatae ullam quas deleniti totam voluptatum, ipsum eum architecto, corporis iure sint voluptatibus esse et magnam. Ratione, inventore delectus!</p>
    </div>
</article>

<style lang="sass">

    $detour-headline-font: Georgia
    $detour-body-font: halyard-display, Segoe UI

    *
        font-family: $detour-body-font
        color: #111111

    article
        max-width: 100%
        position: relative
        margin: 0px 20vw 0 20vw
        display: grid
        justify-items: center
        height: 100%
        h1
            margin: 0 0 20px 0
            padding: 0
            font-size: 40px
            font-family: $detour-headline-font
        h2
            margin: 0 0 20px 0
            padding:0
            width: 100%
        .story::first-letter 
            initial-letter: 3
            margin-right: 0.5em
            font-weight: bold
        .story
            font-weight: regular
            font-size: 20px
            padding: 0 5% 0 5%
        img
            width: 100%
            height: 100%
            object-fit: cover
            object-position: center
        


</style>